main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah-rumah-sakit/', views.rumahsakit, name='rumahsakit'),
    path('tambah-volunteer/<int:id>', views.volunteer, name='volunteer'),
]

volunteer_sultan/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Volunteer(models.Model):
    nama_Volunteer = models.CharField(max_length=100)
    KTP = models.CharField(max_length=100)
    alasan = models.TextField()
    class Meta:
        ordering = ['nama_Volunteer']

class RumahSakit(models.Model):
    nama_Rumah_Sakit = models.CharField(max_length=100)
    alamat = models.CharField(max_length=300)
    telepon = models.CharField(max_length=100)
    gambar = models.ImageField(upload_to='images/', null=True, blank=True)
    volunteer = models.ManyToManyField(Volunteer)
    class Meta:
        ordering = ['nama_Rumah_Sakit']

    def absolute_url(self):
        return reverse("main:volunteer", kwargs = {"id" : self.id})

main/forms.py
from django import forms
from .models import Volunteer, RumahSakit

class FormRumahSakit(forms.ModelForm) :
    class Meta:
        model = RumahSakit
        fields = [
            'nama_Rumah_Sakit',
            'alamat',
            'telepon',
            'gambar',
        ]

        widgets = {
            'nama_Rumah_Sakit' : forms.TextInput(attrs={'class' : 'form-control'}),
            'alamat' : forms.TextInput(attrs={'class' : 'form-control'}),
            'telepon' : forms.NumberInput(attrs={'class' : 'form-control'}),
        }

class FormVolunteer(forms.ModelForm) :
    class Meta:
        model = Volunteer
        fields = [
            'nama_Volunteer',
            'KTP',
            'alasan',
        ]

        widgets = {
            'nama_Volunteer' : forms.TextInput(attrs={'class' : 'form-control'}),
            'KTP' : forms.TextInput(attrs={'class' : 'form-control'}),
            'alasan' : forms.Textarea(attrs={'class' : 'form-control', 'rows':4}),
        }

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import RumahSakit, Volunteer
from .forms import FormRumahSakit, FormVolunteer
from django.http import HttpResponseRedirect

def home(request):
    tRumahSakit = RumahSakit.objects.all()
    context = {
        "rumahsakit" : tRumahSakit
    }
    return render(request, 'main/home.html', context)

def rumahsakit(request):
    form = FormRumahSakit()

    if request.method == "POST":
        form = FormRumahSakit(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("/")
    
    context = {
        "form" : form,
    }
    return render(request, 'main/tambahRS.html', context)

def volunteer(request, *args, **kwargs):
    form = FormVolunteer()

    if request.method == "POST":
        nama_Volunteer = request.POST.get("nama_Volunteer")
        KTP = request.POST.get("KTP")
        alasan = request.POST.get("alasan")
        volunteerDaftar = Volunteer.objects.create(nama_Volunteer = nama_Volunteer, KTP = KTP, alasan = alasan)
        rumahsakit = RumahSakit.objects.get(id = kwargs["id"])
        rumahsakit.volunteer.add(volunteerDaftar)
        return redirect("/")
    
    
    context = {
        "form" : form,
    }

    return render(request, "main/tambahVolunteer.html", context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Volunteer</title>
<style>
  .card{
    background-color: #ededed;
    color: black;
  }

  #card{
    transition: transform 0.01s;
  }

  #card:hover{
    transform: scale(1.01);
  }

  #table{
    color: black;
  }
</style>
{% endblock meta %}

{% block content %}
<h1 class="text-center mb-5">Volunteer</h1>

<div class="container">
  <div class="row">
    
    {% for rs in rumahsakit %}
    <div class="col mb-4 ml-4">
      <div class="card p-0 shadow rounded" id="card" style="width: 18rem; border: solid 2px #48d9ca;">
        <img src="{{rs.gambar.url}}" class="card-img-top" alt="{{rs.nama_Rumah_Sakit}}" style="height: 11rem;">
        <div class="card-body">
          <h5 class="card-title text-center mt-0 mb-0" id="card-title">{{rs.nama_Rumah_Sakit}}</h5>
          <table class="table table-borderless mt-1 mb-1" id="table">
            <tbody>
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-map-marker" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.alamat}}</td>
              </tr>
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-phone" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.telepon}}</td>
              </tr>      
              <tr>
                <th scope="row" class="pt-1"><i class="fa fa-user" aria-hidden="true"></i></th>
                <td class="pt-1">{{rs.volunteer.all|length}} Volunteer</td>
              </tr>
            </tbody>
          </table>
          <div class="text-center">
            <a href="{{rs.absolute_url}}" class="btn btn-primary text-center">Daftar Volunteer</a>
          </div>
        </div>
      </div>
    </div>  
    {% endfor %}
    <div class="col text-center">
      <a href="{% url 'main:rumahsakit' %}" class="btn btn-primary btn-lg">Tambah Rumah Sakit</a> 
    </div>
  </div>
    
</div>
{% endblock content %}

main/templates/main/tambahRS.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1 class="text-center mb-3">Tambah Rumah Sakit</h1>
    <div class="container p-3" style="background-color: #48d9ca; color: white;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="col-md-12">
                <input class="btn btn-primary" type="submit" value="Tambah">
                <a href="{% url 'main:home' %}" class="btn btn-danger">Kembali</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/tambahVolunteer.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1 class="text-center mb-3">Tambah Volunteer</h1>
    <div class="container p-3" style="background-color: #48d9ca; color: white;">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="col-md-12">
                <input class="btn btn-primary" type="submit" value="Daftar">
                <a href="{% url 'main:home' %}" class="btn btn-danger">Kembali</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- link buat bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- link buat icon -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <!-- script buat bootstrap -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>